# Generated by Django 4.0 on 2024-04-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_ipaddress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ipaddress',
            table='ip_addresses',
        ),
    ]
