# Generated by Django 4.0 on 2024-04-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0009_alter_ipaddress_address_alter_ipaddress_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='address',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
