# Generated by Django 4.0 on 2024-04-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0010_alter_ipaddress_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='address',
            field=models.CharField(max_length=45),
        ),
    ]
